version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: gunicorn -w 4 -b 0.0.0.0:8080 app:app  # Adjust 'app:app' to match your Flask app entry point

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
